### ISSUE TITLE
`./es6-promise.map` polyfill warning with Webpack / TypeScript

### ISSUE THREAD

**Issue by Nevraeka** [contentful/contentful.js#145]
The polyfill for Promise seems unreachable. Please advise on how to fix this warning. Thanks in advance.  cc @TheLarkInn

* **Node Version**: 6.8
* **Npm Version**: 3.10.8
* **Platform**: V-061G8WP 16.0.0 Darwin Kernel Version 16.0.0
* **Package Version**: contentful@4.3.0

#### Webpack output (with some altered paths & names)
```
WARNING in ./~/contentful/dist/contentful.js
(Emitted value instead of an instance of Error) Cannot find SourceMap 'es6-promise.map': Error: Can't resolve './es6-pro
mise.map' in '/node_modules/contentful/dist'
 @ ./app/utils/contentfulConnector.tsx 6:19-40
 @ ./app/containers/FeatureX/index.tsx
 @ ./app/containers/App/index.tsx
 @ ./app/app.tsx
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/app.tsx
```

**Comment by Khaledgarbaya** [comment]
Hi @Nevraeka,
Looks like you are using typescript.
can you share your `webpack.config` and `tsconfig`

Best,
Khaled

**Comment by Nevraeka** [comment]
@Khaledgarbaya thank you 
#### TSCONFIG
```
{
    "compilerOptions": {
        "outDir": "./build/",
        "sourceMap": true,
        "noImplicitAny": false,
        "module": "commonjs",
        "moduleResolution": "node",
        "target": "es5",
        "jsx": "react",
        "experimentalDecorators": true,
        "removeComments": true,
        "allowJs": true,
        "lib": [
            "es2017",
            "dom"
        ],
        "typeRoots": [
            "node_modules/@types",
            "custom-typings",
            "typings/globals"
        ]
    },
    "awesomeTypescriptLoaderOptions": {
        "useWebpackText": true
    },
    "exclude": [
        "node_modules"
    ],
    "include": [
        "./app/**/*"
    ]
}
```
#### Webpack (base modified from react-boilerplate w/ custom scss modified)
```
/**
 * COMMON WEBPACK CONFIGURATION
 */

const path = require('path');
const webpack = require('webpack');
const { CheckerPlugin } = require('awesome-typescript-loader');

module.exports = options => ({
  entry: options.entry,
  output: Object.assign({
    path: path.resolve('build'),
    filename: 'app.js',
    publicPath: '/',
  }, options.output),
  module: {
    rules: [
      {
        test: /.(scss|css)$/,
        enforce: 'pre',
        use: [
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader',
            options: { importLoaders: 1 }
          },
          {
            loader: 'sass-loader',
            options: {
              includePaths: [
                `${process.cwd()}/node_modules/custom1`,
                `${process.cwd()}/node_modules/custom2`
              ],
              sourceMap: true
            }
          }
        ]
      },
      {
        test: /\.tsx?$/,
        exclude: /node_modules/,
        loaders: ['react-hot-loader', 'awesome-typescript-loader'],
      },
      {
        enforce: 'pre',
        test: /\.js$/,
        loader: 'source-map-loader',
      },
    ],
    loaders: [{
      test: /\.(eot|svg|ttf|woff|woff2)$/,
      loader: 'file-loader',
    }, {
      test: /\.(jpg|png|gif)$/,
      loaders: [
        'file-loader',
        {
          loader: 'image-webpack-loader',
          query: {
            progressive: false,
            optimizationLevel: 7,
            interlaced: false,
            pngquant: {
              quality: '65-90',
              speed: 4,
            },
          },
        },
      ],
    }, {
      test: /\.html$/,
      loader: 'html-loader',
    }, {
      test: /\.json$/,
      loader: 'json-loader',
    }, {
      test: /\.(mp4|webm)$/,
      loader: 'url-loader',
      query: {
        limit: 10000,
      },
    }],
  },
  plugins: options.plugins.concat([
    new webpack.ProvidePlugin({
      fetch: 'exports-loader?self.fetch!whatwg-fetch',
    }),
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify(process.env.NODE_ENV),
      },
    }),
    new webpack.NamedModulesPlugin(),
    new CheckerPlugin(),
  ]),
  resolve: {
    modules: [
      'app',
      'node_modules',
    ],
    extensions: [
      '.scss',
      '.ts',
      '.tsx',
      '.js',
      '.jsx',
      '.react.js',
      '.json',
    ],
    mainFields: [
      'browser',
      'jsnext:main',
      'main',
    ],
  },
  devtool: options.devtool,
  target: 'web', // Make web variables accessible to webpack, e.g. window
  performance: options.performance || {},
});
```

**Comment by Khaledgarbaya** [comment]
Hi @Nevraeka,
what is the value of your `devtool` property, I think if you set it to `source-map` it should fix the issue

**Comment by Nevraeka** [comment]
@Khaledgarbaya thanks for responding again. The value was set as `inline-source-map`. I tried the value as `source-map` and it still does not work. I think it is pointing to the `node_modules/contentful/dist` dir looking for the `es6-promise.map` file (which does not exist in the module) 

This is where I was looking in my code that led to that conclusion. Is the map file supposed to get built in the dist directory for contentful?
```
(Emitted value instead of an instance of Error) Cannot find SourceMap 'es6-promise.map': Error: Can't resolve './es6-pro
mise.map' in '/node_modules/contentful/dist'
```

**Comment by Khaledgarbaya** [comment]
Hi @Nevraeka ,
I made a PR that should fix this issue. It would so kind if you can test it in you setup before we release a new fix
here is the link https://github.com/contentful/contentful.js/pull/146.

Best,
Khaled

**Comment by Khaledgarbaya** [comment]
This is fixed in https://github.com/contentful/contentful.js/pull/146
