### ISSUE TITLE
Response size too big. Maximum allowed response size: 7340032b

### ISSUE THREAD

**Issue by brijmcq** [contentful/contentful.js#336]
## Expected Behavior

Calling client.getEntries should get all of my data.

## Actual Behavior
I'm getting this error message `Response size too big. Maximum allowed response size: 7340032b.`

## Possible Solution
Here's my config when calling the `getEntries` function
`await client.getEntries({content_type: 'xxxx', include: 3});`
I know that the `include:3` causes it to make the response size too big but we have some functions where we need our data all at once. I could have set a `first` or `skip` here but it is not an option right now 

It would be nice if there's a way to override the  maximum allowed response size
## Steps to Reproduce
Just have a large set of data without any filtering or pagination.

## Context

When we were starting with Contentful 6 months ago, we only had a few data so this was not an issue. We're using Hugo to generate our web pages and we generate the md and json files using Contentful.

## Environment

-   **Language Version**: v11.4.0
-   **Package Manager Version**: 6.9.0
-   **Operating System**:  Ubuntu 18
-   **Package Version**: ^7.9.1
-   **Which API are you using?**: Delivery

**Comment by Khaledgarbaya** [comment]
Hi @brijmcq,
you can reduce the number of entries per page 
`await client.getEntries({limit: 50})` and keep the include value

**Comment by brijmcq** [comment]
thanks @Khaledgarbaya . My workaround is something like this
```
  const data1 = await client.getEntries({ content_type: 'xxxx', include: 3, limit: 10 });
  const data2 = await client.getEntries({ content_type: 'xxxx', include: 3, skip: 10 });
  const allData = {};
  allData.items = [...data1.items, ...data2.items];
```

**Comment by marcus13371337** [comment]
I'm having this issue as well. Unfortunately, I'm getting just one entry with a lot of references to other entries. What's weird is that I'm getting the response with no problem when I'm using the API directly.

**Comment by marcus13371337** [comment]
Did some investigation. It seems as `axios`, default size is 10Mb. However, this is fixed in `contentful-sdk-core` as they are setting that parameter to 1 GB in version `6.8.0` (https://github.com/contentful/contentful-sdk-core/commit/9c69b6c33b636d447fc90bd0fd02f72544cfefde).

Submitted a PR to bump this package

**Comment by marcus13371337** [comment]
Never mind,  `maxContentLength` should already be configurable!

**Comment by jwugit** [comment]
was this merged or something is missing, 
i'm seeing the package for contentful-sdk-core is at v7
but im still encountering the same error 


```
BadRequest: {
  "status": 400,
  "statusText": "",
  "message": "Response size too big. Maximum allowed response size: 7340032B.",
  "details": {},
  "request": {
    "url": "entries",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "X-Contentful-User-Agent": "sdk contentful.js/9.1.10; platform browser; os Windows;",
      "Authorization": "Bearer ...c5e53"
    },
    "method": "get"
  },
  "requestId": "ba76ab2c-5db1-4480-8459-c63bd2ba94fb"
}
```

**Comment by nomatter2challenge** [comment]
> 

Same here.

**Comment by jwugit** [comment]
for anyone looking into this in the future, 
it might be due to contentful technical limits.
![image](https://user-images.githubusercontent.com/28541026/157791576-bf9f2477-293a-48f8-90cd-195d9964338a.png)

https://www.contentful.com/developers/docs/technical-limits/
