### ISSUE TITLE
Title of the documentation is overlapping.

### ISSUE THREAD

**Issue by unixisking** [contentful/contentful.js#406]
Hello :) 

The title in the  [home page](https://contentful.github.io/contentful.js/contentful/7.14.4/) of the documentation is overlapping like so:
![pic-selected-200506-0956-08](https://user-images.githubusercontent.com/13711044/81153761-243dca00-8f7b-11ea-886e-388f0b2d7d87.png)

There's also a typo in the jsdoc.css file for version 7.14.4

![pic-selected-200506-1026-22](https://user-images.githubusercontent.com/13711044/81154350-b8a82c80-8f7b-11ea-860d-b31dade5180c.png)

**Comment by marcolink** [comment]
Hi @sidou01, can you confirm that this is fixed?

**Comment by sidou01** [comment]
Hello @marcolink, this is still an issue even in the newer version 7.14.6

**Comment by marcolink** [comment]
@unixisking please feel free to create a PR for the fix. 
For the upcoming version `10.0.0` we have already revised all doc files 😎
